# Generated by Django 6.0.2 on 2026-02-20 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('monthly_income', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_limit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_debt', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='loans_custo_phone_n_cdb6bd_idx'), models.Index(fields=['customer_id'], name='loans_custo_custome_59efb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tenure', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_installment', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('emis_paid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='loans_loan_custome_9efb67_idx'), models.Index(fields=['loan_id'], name='loans_loan_loan_id_4268fd_idx')],
            },
        ),
    ]
